name: PR Checks
on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache Rust
        uses: Swatinem/rust-cache@v1

      - name: Test Rust
        run: cargo test

      - name: Build Rust
        run: cargo build --release