name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Test Rust
        run: |
          # features=graphql_parser_fork
          cargo test --features graphql_parser_fork --no-default-features
          # features=graphql_parser
          cargo test

      - name: Build Rust
        run: |
          # features=graphql_parser_fork
          cargo build --release --features graphql_parser_fork --no-default-features
          # features=graphql_parser
          cargo build --release
